"""explanations

Revision ID: da53dbbe6f84
Revises: 32aefa6a5c84
Create Date: 2023-12-09 17:38:56.557167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "da53dbbe6f84"
down_revision: Union[str, None] = "32aefa6a5c84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("explanation", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "explanation")
    # ### end Alembic commands ###
