"""rename reward to exp

Revision ID: 962e9ce075dd
Revises: 8bd28c795ab0
Create Date: 2023-12-09 01:15:58.882662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "962e9ce075dd"
down_revision: Union[str, None] = "8bd28c795ab0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("exp", sa.Integer(), nullable=False))
    op.drop_column("tasks", "reward")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("reward", sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column("tasks", "exp")
    # ### end Alembic commands ###
