"""integer array for correct choices

Revision ID: bc9e80ccce23
Revises: 8c2668411a39
Create Date: 2023-12-08 16:14:20.468163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bc9e80ccce23"
down_revision: Union[str, None] = "8c2668411a39"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "correct_choices",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        type_=postgresql.ARRAY(sa.Integer()),
        existing_nullable=True,
        postgresql_using="correct_choices::integer[]",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "correct_choices",
        existing_type=postgresql.ARRAY(sa.Integer()),
        type_=postgresql.ARRAY(sa.VARCHAR()),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
