"""add aliases

Revision ID: ed6fdb3d02c5
Revises: caa3b896473e
Create Date: 2023-12-08 15:55:39.188347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed6fdb3d02c5"
down_revision: Union[str, None] = "caa3b896473e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lessons", sa.Column("alias", sa.String(), nullable=False))
    op.add_column("lessons", sa.Column("title", sa.String(), nullable=False))
    op.create_unique_constraint(None, "lessons", ["alias"])
    op.add_column("tasks", sa.Column("alias", sa.String(), nullable=False))
    op.add_column("tasks", sa.Column("title", sa.String(), nullable=False))
    op.create_unique_constraint(None, "tasks", ["alias"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="unique")
    op.drop_column("tasks", "title")
    op.drop_column("tasks", "alias")
    op.drop_constraint(None, "lessons", type_="unique")
    op.drop_column("lessons", "title")
    op.drop_column("lessons", "alias")
    # ### end Alembic commands ###
