"""add lessons

Revision ID: caa3b896473e
Revises: b2390175ad0f
Create Date: 2023-12-08 14:55:38.909351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "caa3b896473e"
down_revision: Union[str, None] = "b2390175ad0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lessons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("difficulty", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_lessons_id"), "lessons", ["id"], unique=False)
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column(
            "type", sa.Enum("empty", "instant", "radio", "multichoice", "input", name="steptype"), nullable=False
        ),
        sa.Column("choices", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("correct_choices", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("input_answers", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("reward", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tasks_id"), "tasks", ["id"], unique=False)
    op.create_table(
        "task_association",
        sa.Column("test_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["test_id"],
            ["lessons.id"],
        ),
        sa.PrimaryKeyConstraint("test_id", "task_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_association")
    op.drop_index(op.f("ix_tasks_id"), table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_lessons_id"), table_name="lessons")
    op.drop_table("lessons")
    # ### end Alembic commands ###
