"""remove many to many

Revision ID: 870cb6770042
Revises: e704f0004b10
Create Date: 2023-12-09 11:34:29.650046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "870cb6770042"
down_revision: Union[str, None] = "e704f0004b10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("battle_pass_levels")
    op.add_column("level", sa.Column("battle_pass_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "level", "battle_pass", ["battle_pass_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "level", type_="foreignkey")
    op.drop_column("level", "battle_pass_id")
    op.create_table(
        "battle_pass_levels",
        sa.Column("battle_pass_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("level_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["battle_pass_id"], ["battle_pass.id"], name="battle_pass_levels_battle_pass_id_fkey"),
        sa.ForeignKeyConstraint(["level_id"], ["level.id"], name="battle_pass_levels_level_id_fkey"),
        sa.PrimaryKeyConstraint("battle_pass_id", "level_id", name="battle_pass_levels_pkey"),
    )
    # ### end Alembic commands ###
