"""add date end

Revision ID: 32aefa6a5c84
Revises: a7c05d6b50c2
Create Date: 2023-12-09 17:07:49.470530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "32aefa6a5c84"
down_revision: Union[str, None] = "a7c05d6b50c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("battle_pass", sa.Column("date_end", sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("battle_pass", "date_end")
    # ### end Alembic commands ###
